image: docker:stable
services:
  - docker:18.09.7-dind
variables:
  CI_REGISTRY_NAME: "$VAR_REGISTRY/basys/ppr-dashboard"

deploy_production:
  stage: deploy
  before_script:
   - docker login -u "$VAR_REGISTRY_USER" -p "$VAR_REGISTRY_PASSWORD" "$VAR_REGISTRY"
  script:
  - docker build -t "$CI_REGISTRY_NAME:latest"
  - docker push "$CI_REGISTRY_NAME:latest"
  only:
  - master
