deploy_production:
  stage: deploy
  image: docker:dind
  variables:
    CI_REGISTRY_NAME: "$VAR_REGISTRY/basys/ppr-dashboard"
  before_script:
   - docker login -u "$VAR_REGISTRY_USER" -p "$VAR_REGISTRY_PASSWORD" "$VAR_REGISTRY"
  script:
  - docker build -t "$CI_REGISTRY_NAME:latest"
  - docker push "$CI_REGISTRY_NAME:latest"
  only:
  - master
