stages:
  - test
  - build

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375" 
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY_NAME: '$DOCKER_REGISTRY/dfkibasys/ppr-dashboard'
  TARGET_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

test:
  image: cypress/base:16.14.2
  stage: test
  script:
    - npm install
    - npm run test
  tags:
    - basys

build:
  image: docker:20.10.17
  stage: build
  services:
    - name: docker:20.10.12-dind
       # explicitly disable tls to avoid docker startup interruption
      command: ["--tls=false"]

  tags:
    - basys
    - docker
  script:
    - docker context create build-ctx
    - docker buildx create build-ctx --use
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - docker buildx build --platform $TARGET_PLATFORMS -t "$CI_REGISTRY_NAME:latest" . --push
  only:
    - master

build-dev:
  image: docker:20.10.17
  stage: build
  services:
    - name: docker:20.10.12-dind
       # explicitly disable tls to avoid docker startup interruption
      command: ["--tls=false"]
  tags:
    - basys
    - docker
  script:
    - docker context create build-ctx
    - docker buildx create build-ctx --use
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - docker buildx build --platform $TARGET_PLATFORMS -t "$CI_REGISTRY_NAME:dev" . --push
  only:
    - develop
