image: docker:19.03.6
services:
  - docker:19.03.6-dind
variables:
  CI_REGISTRY_NAME: "$VAR_REGISTRY/basys/ppr-dashboard"
  DOCKER_TLS_CERTDIR: "/certs"
deploy_production:
  stage: deploy
  before_script:
   - docker login -u "$VAR_REGISTRY_USER" -p "$VAR_REGISTRY_PASSWORD" "$VAR_REGISTRY"
  script:
  - docker build -t "$CI_REGISTRY_NAME:latest"
  - docker push "$CI_REGISTRY_NAME:latest"
  only:
  - master
