stages:
  - test
  - build

variables:
  DOCKER_HOST: tcp://docker:2376
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and
  # build container.
  DOCKER_TLS_CERTDIR: '/certs'
  CI_REGISTRY_NAME: '$DOCKER_REGISTRY/dfkibasys/ppr-dashboard'

test:
  image: cypress/base:16.14.2
  stage: test
  script:
    - npm install
    - npm run test
  tags:
    - basys

build:
  image: docker:20.10.17
  stage: build
  services:
    - docker:20.10.17-dind
  tags:
    - basys
    - docker
  script:
    - docker context create build-ctx
    - docker buildx create build-ctx --use
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"  "$DOCKER_REGISTRY"
    - docker buildx build --platform linux/arm64/v8,linux/amd64 -t "$CI_REGISTRY_NAME:latest" . --push
  only:
    - master

build-dev:
  image: docker:20.10.17
  stage: build
  services:
    - docker:20.10.17-dind
  tags:
    - basys
    - docker
  script:
    - docker context create build-ctx
    - docker buildx create build-ctx --use
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"  "$DOCKER_REGISTRY"
    - docker buildx build --platform linux/arm64/v8,linux/amd64 -t "$CI_REGISTRY_NAME:dev" . --push
  only:
    - develop
