image: docker:20.10.12

variables:
  DOCKER_HOST: tcp://docker:2376
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and
  # build container.
  DOCKER_TLS_CERTDIR: '/certs'
  CI_REGISTRY_NAME: '$REGISTRY/dfkibasys/ppr-dashboard'

services:
  - docker:20.10.12-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" "$REGISTRY"
    - docker build -t "$CI_REGISTRY_NAME:latest" .
    - docker push "$CI_REGISTRY_NAME:latest"
  only:
    - master

build-dev:
  stage: build
  script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" "$REGISTRY"
    - docker build -t "$CI_REGISTRY_NAME:dev" .
    - docker push "$CI_REGISTRY_NAME:dev"
  only:
    - develop
