stages:
  - test
  - build

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: 'tcp://docker:2375'
  DOCKER_TLS_CERTDIR: ''
  CI_REGISTRY_NAME: '$DOCKER_REGISTRY/dfkibasys/ppr-dashboard'
  DOCKER_FILE_NAME: Dockerfile
  TARGET_PLATFORMS: linux/amd64,linux/arm64

test:
  image: cypress/browsers:node-20.15.1-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
  stage: test
  script:
    - npm install
    - npm run test
  tags:
    - basys

build:
  image: docker:27.0.3
  stage: build
  services:
    - name: docker:27.0.3-dind
      # explicitly disable tls to avoid docker startup interruption
      command: ['--tls=false']

  tags:
    - basys
    - docker
  script:
    - docker context create build-ctx
    - docker buildx create build-ctx --use
    # fix potential win / linux line ending problems otherwise it will not be executable
    - sed -i 's/\r$//' ./entrypoint.sh
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
    - docker buildx build --platform $TARGET_PLATFORMS -t "$CI_REGISTRY_NAME:latest" -f $DOCKER_FILE_NAME . --push
  only:
    - master

build-dev:
  image: docker:27.0.3
  stage: build
  services:
    - name: docker:27.0.3-dind
      # explicitly disable tls to avoid docker startup interruption
      command: ['--tls=false']
  tags:
    - basys
    - docker
  script:
    - docker context create build-ctx
    - docker buildx create build-ctx --use
    # fix potential win / linux line ending problems otherwise it will not be executable
    - sed -i 's/\r$//' ./entrypoint.sh
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
    - docker buildx build --platform $TARGET_PLATFORMS -t "$CI_REGISTRY_NAME:dev" -f $DOCKER_FILE_NAME . --push
  only:
    - develop

build-stable:
  image: docker:27.0.3
  stage: build
  services:
    - name: docker:27.0.3-dind
      # explicitly disable tls to avoid docker startup interruption
      command: ['--tls=false']
  tags:
    - basys
    - docker
  script:
    - docker context create build-ctx
    - docker buildx create build-ctx --use
    # fix potential win / linux line ending problems otherwise it will not be executable
    - sed -i 's/\r$//' ./entrypoint.sh
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
    - docker buildx build --platform $TARGET_PLATFORMS -t "$CI_REGISTRY_NAME:$CI_COMMIT_TAG" -f $DOCKER_FILE_NAME . --push
  only:
    - tags
